### ISSUE TITLE
TypeError: get() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by fcrozat** [saltstack-formulas/postgres-formula#141] opened 2017-01-25 21:12 UTC
When trying to use postgres-formula on openSUSE Leap 42.2 (which ships with 2016.3.4), I got the following error:
- Rendering SLS 'base:postgres.manage' failed: Jinja error: get() takes exactly 3 arguments (2 given)
      Traceback (most recent call last):
        File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
          output = template.render(**decoded_context)
        File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
          return self.environment.handle_exception(exc_info, True)
        File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
          reraise(exc_type, exc_value, tb)
        File "<template>", line 4, in top-level template code
      TypeError: get() takes exactly 3 arguments (2 given)
      
      ; line 4
      
      ---
      {%- from "postgres/map.jinja" import postgres with context -%}
      {%- from "postgres/macros.jinja" import format_state with context -%}
      
      {%- if not salt.get('postgres.user_create') %}    <======================
      
      # Salt states for managing PostgreSQL is not available,
      # need to provision client binaries first
      
      include:
      [...]

**Comment by YetAnotherMinion** [comment] 2017-02-06 17:04
probably wants a default argument, which in this case would be

```
{%- if not salt.get('postgres.user_create', False) %}
```

**Comment by vutny** [comment] 2017-02-07 11:15
@fcrozat Thanks for you report.

I've tested the code with Salt `2016.3.4` and `2016.11.1` many times and it always works fine for me. Maybe it is related to particular `jinja` module version installed...

Try to replace the line with the following:
```jinja
{%- if 'postgres.user_create' not in salt.keys() %}
```

I hope this will help. If so, we update the code accordingly.

**Comment by fcrozat** [comment] 2017-02-11 14:13
changing to {%- if not salt.get('postgres.user_create', False) %}  works fine.

other proposed fix ( %- if 'postgres.user_create' not in salt.keys() %} )doesn't work:

- Rendering SLS 'base:postgres.manage' failed: Jinja error: 'FunctionWrapper' object has no attribute '__call__'
      Traceback (most recent call last):
        File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
          output = template.render(**decoded_context)
        File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
          return self.environment.handle_exception(exc_info, True)
        File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
          reraise(exc_type, exc_value, tb)
        File "<template>", line 5, in top-level template code
      AttributeError: 'FunctionWrapper' object has no attribute '__call__'
      
      ; line 5
      
      ---
      {%- from "postgres/map.jinja" import postgres with context -%}
      {%- from "postgres/macros.jinja" import format_state with context -%}
      
      {# }{%- if not salt.get('postgres.user_create') %} #}
      {%- if 'postgres.user_create' not in salt.keys() %}    <======================
      
      # Salt states for managing PostgreSQL is not available,
      # need to provision client binaries first
      
      include:
      [...]
      ---

**Comment by vutny** [comment] 2017-02-11 16:04
@fcrozat Thanks a lot for testing.
This is very interesting, it looks like ordinary Python methods cannot be reliably used for special Jinja objects such as `salt`, at least in your case. And I think the `get()` method cannot be fully trusted here to do the job I thought it was supposed to do.

Please, could you try the last one code snippet since only you are able to reproduce the issue?
Check this out if it would work:
```jinja
{%- if salt['postgres.user_create']|default(none) is not callable %}
```

I assume this is the safest check for the exec module function present (and actually is a function) in the state run scope.

Thanks again for your involvement.

**Comment by fcrozat** [comment] 2017-02-13 13:03
I can confirm the latest proposed fix works fine here.

**Comment by vutny** [comment] 2017-02-13 13:20
Cool! That was very helpful, @fcrozat. Soon I will come up with a PR to fix this and other similar calls to the `salt` object across the formula.

**Comment by vutny** [comment] 2017-02-17 09:43
@fcrozat PR #150 has been merged. I think this issue could be closed. Thanks for your participation!

**Comment by vutny** [comment] 2017-03-29 10:35
@javierbertoli Since this is already resolved, please close it out. Thanks!

**Closed** 2017-03-29 10:56 UTC
